version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app_network
  
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
    networks:
      - app_network

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis
    networks:
      - app_network

networks:
  app_network:
